# Generated by Django 5.0.6 on 2026-10-04 18:10

import uuid

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryBucket",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("capacity", models.PositiveIntegerField()),
                ("held_count", models.PositiveIntegerField(default=0)),
                ("sold_count", models.PositiveIntegerField(default=0)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="inventory", to="events.event"
                    ),
                ),
                (
                    "ticket_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory",
                        to="events.eventtickettype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeatClaim",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "state",
                    models.CharField(choices=[("HELD", "Held"), ("SOLD", "Sold")], default="HELD", max_length=4),
                ),
                ("expires_at", models.DateTimeField(null=True)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="events.event")),
                (
                    "event_seat",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, related_name="claim", to="events.eventseat"
                    ),
                ),
                (
                    "reservation_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claim",
                        to="reservations.reservationitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeatClaimHistory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("action", models.CharField(max_length=20)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="events.event")),
                ("event_seat", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="events.eventseat")),
                (
                    "reservation_item",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="reservations.reservationitem"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="inventorybucket",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "capacity__gte",
                        django.db.models.expressions.CombinedExpression(
                            models.F("held_count"), "+", models.F("sold_count")
                        ),
                    )
                ),
                name="inventory_within_capacity",
            ),
        ),
        migrations.AddConstraint(
            model_name="seatclaim",
            constraint=models.CheckConstraint(
                check=models.Q(("state__in", ["HELD", "SOLD"])), name="seat_claim_valid_state"
            ),
        ),
    ]
