# Generated by Django 5.0.6 on 2026-10-04 18:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("CONSUMED", "Consumed"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("fingerprint", models.CharField(max_length=64)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="reservations", to="events.event"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReservationItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("quantity", models.PositiveSmallIntegerField()),
                ("unit_price_minor", models.PositiveIntegerField()),
                ("currency", models.CharField(max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("CONSUMED", "Consumed"), ("RELEASED", "Released")],
                        default="ACTIVE",
                        max_length=8,
                    ),
                ),
                (
                    "event_seat",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="events.eventseat"
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="reservations.reservation",
                    ),
                ),
                (
                    "ticket_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="events.eventtickettype"),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(fields=["event", "status", "expires_at"], name="reservation_event_i_6df568_idx"),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(fields=("user", "idempotency_key"), name="unique_user_hold_key"),
        ),
        migrations.AddConstraint(
            model_name="reservationitem",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gt", 0)), name="reservation_quantity_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="reservationitem",
            constraint=models.CheckConstraint(
                check=models.Q(("event_seat__isnull", True), ("quantity", 1), _connector="OR"),
                name="assigned_quantity_one",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservationitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("event_seat__isnull", False)),
                fields=("reservation", "event_seat"),
                name="one_seat_per_hold",
            ),
        ),
    ]
