import { useState } from 'react';
import { Text, View } from 'react-native';
import { useQuery } from '@tanstack/react-query';
import { useLocalSearchParams } from 'expo-router';
import type { Organization, Paginated, Profile } from '../../packages/api-client/src';
import { post } from '../../packages/api-client/src';
import { useSession } from '../src/session';
import { Alert, Button, Input, Loading, Page, styles } from '../src/ui';

export default function Account() {
  const { user, ready, api, login, logout, updateProfile } = useSession(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [name, setName] = useState(''); const [register, setRegister] = useState(false); const [error, setError] = useState<unknown>(null); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(''); const [token, setToken] = useState(''); const [invitation, setInvitation] = useState('');
  const params = useLocalSearchParams<{ verify?: string; reset?: string; user_id?: string; invitation?: string }>();
  const organizations = useQuery({ queryKey: ['organizations', user?.id], queryFn: () => api<Paginated<Organization>>('/organizations/'), enabled: !!user });
  async function action(callback: () => Promise<unknown>, success = '') { setBusy(true); setError(null); try { await callback(); setNotice(success); } catch (err) { setError(err); } finally { setBusy(false); } }
  if (!ready) return <Page title="Your account"><Loading /></Page>;
  return <Page title={user ? `Hello, ${user.display_name || user.email}.` : 'Your account'}><Alert error={error} />{notice ? <Text accessibilityRole="alert" style={styles.notice}>{notice}</Text> : null}{params.reset && <View style={styles.card}><Text style={styles.subtitle}>Reset your password</Text><Input label="New password" value={password} onChangeText={setPassword} secret /><Button title="Set new password" disabled={busy} onPress={() => void action(() => api('/auth/password-reset/confirm/', post({ user_id: params.user_id, token: params.reset, password })), 'Password changed. Sign in again.')} /></View>}
  {!user ? <View style={styles.card}><Text style={styles.subtitle}>{register ? 'Create your account' : 'Welcome back'}</Text>{register && <Input label="Display name" value={name} onChangeText={setName} />}<Input label="Email" value={email} onChangeText={setEmail} keyboard="email-address" /><Input label="Password" value={password} onChangeText={setPassword} secret /><Button title={register ? 'Create account' : 'Sign in'} disabled={busy} onPress={() => void action(async () => { if (!email.trim() || !password) throw new Error('Enter your email and password.'); await login(email, password, register ? name : undefined); setPassword(''); })} /><Button title={register ? 'Already have an account? Sign in' : 'New here? Create an account'} disabled={busy} onPress={() => setRegister(!register)} /><Button title="Send password reset email" disabled={busy || !email.trim()} onPress={() => void action(() => api('/auth/password-reset/', post({ email })), 'If the account exists, an email has been queued.')} /></View> : <>
  {!user.email_verified_at && <View style={styles.card}><Text style={styles.text}>Verify your email before reserving tickets.</Text><Button title="Send verification email" disabled={busy} onPress={() => void action(() => api('/auth/email-verification/', post({})), 'Verification email queued.')} /><Input label="Verification token" value={token || params.verify || ''} onChangeText={setToken} /><Button title="Verify email" disabled={busy} onPress={() => void action(async () => { await api('/auth/email-verify/', post({ token: token || params.verify })); updateProfile(await api<Profile>('/me/')); }, 'Email verified.')} /></View>}
  <View style={styles.card}><Text style={styles.subtitle}>Your organizations</Text><Alert error={organizations.error} />{organizations.data?.results.map(org => <View key={org.id}><Text style={styles.text}>{org.name}</Text><Text style={styles.muted}>{org.role}</Text></View>)}{organizations.data && !organizations.data.results.length && <Text style={styles.muted}>No organization memberships yet. Create a workspace on the web.</Text>}<Input label="Invitation token" value={invitation || params.invitation || ''} onChangeText={setInvitation} /><Button title="Accept invitation" disabled={busy || !user.email_verified_at} onPress={() => void action(() => api('/invitations/accept/', post({ token: invitation || params.invitation })), 'Invitation accepted. Refresh your account to see the new workspace.')} /></View><Button title="Sign out" disabled={busy} onPress={() => void action(logout)} />
  </>}
  </Page>;
}
