import { useEffect, useState } from 'react';
import { Image, Linking, Platform, Text, View } from 'react-native';
import { useInfiniteQuery, useQuery, useQueryClient } from '@tanstack/react-query';
import { File, Paths } from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import type { Notification, Order, Paginated, Ticket } from '../../packages/api-client/src';
import { money, post } from '../../packages/api-client/src';
import { useSession } from '../src/session';
import { Alert, Button, Loading, Page, SignInPrompt, styles } from '../src/ui';

function TicketCard({ ticket }: { ticket: Ticket }) {
  const { protectedSource, api } = useSession(); const [source, setSource] = useState<{ uri: string; headers?: { Authorization: string } }>(); const [error, setError] = useState<unknown>(null); const [busy, setBusy] = useState(false);
  useEffect(() => { let active = true; let url: string | undefined; async function load() { try { if (Platform.OS === 'web') { const blob = await api<Blob>(`/tickets/${ticket.id}/qr/`); url = URL.createObjectURL(blob); if (active) setSource({ uri: url }); } else { const value = await protectedSource(`/tickets/${ticket.id}/qr/`); if (active) setSource(value); } } catch (err) { if (active) setError(err); } } if (ticket.status === 'VALID') void load(); return () => { active = false; if (url) URL.revokeObjectURL(url); }; }, [ticket.id, ticket.status, api, protectedSource]);
  async function download() { setBusy(true); setError(null); try { if (Platform.OS === 'web') { const blob = await api<Blob>(`/tickets/${ticket.id}/pdf/`); const url = URL.createObjectURL(blob); await Linking.openURL(url); setTimeout(() => URL.revokeObjectURL(url), 60000); } else { const authorized = await protectedSource(`/tickets/${ticket.id}/pdf/`); const file = await File.downloadFileAsync(authorized.uri, new File(Paths.cache, `${ticket.public_code}.pdf`), { headers: authorized.headers, idempotent: true }); try { if (!await Sharing.isAvailableAsync()) throw new Error('PDF sharing is unavailable on this device.'); await Sharing.shareAsync(file.uri, { mimeType: 'application/pdf', dialogTitle: 'Your ticket' }); } finally { file.delete(); } } } catch (err) { setError(err); } finally { setBusy(false); } }
  return <View style={styles.card}><Text style={styles.subtitle}>{ticket.event_title}</Text><Text style={styles.text}>{ticket.ticket_type_name} · {ticket.seat_label ?? 'General admission'}</Text><Text style={styles.badge}>{ticket.status} · {ticket.public_code}</Text><Text style={styles.muted}>{new Date(ticket.start_at).toLocaleString()}</Text>{source && ticket.status === 'VALID' && <Image accessibilityLabel={`Admission QR for ${ticket.public_code}`} source={source} style={{ width: 220, height: 220, alignSelf: 'center' }} onError={() => setError(new Error('Unable to load the QR. Refresh your wallet.'))} />}<Alert error={error} /><Button title={`Download PDF ${ticket.public_code}`} disabled={busy} onPress={() => void download()} /></View>;
}
export default function Wallet() {
  const { user, api, ready } = useSession(); const queries = useQueryClient(); const [error, setError] = useState<unknown>(null);
  const tickets = useInfiniteQuery({ queryKey: ['tickets', user?.id], initialPageParam: 1, queryFn: ({ pageParam }) => api<Paginated<Ticket>>(`/tickets/?page=${pageParam}`), getNextPageParam: (page, pages) => page.next ? pages.length + 1 : undefined, enabled: !!user, refetchInterval: 15000 });
  const orders = useInfiniteQuery({ queryKey: ['orders', user?.id], initialPageParam: 1, queryFn: ({ pageParam }) => api<Paginated<Order>>(`/orders/?page=${pageParam}`), getNextPageParam: (page, pages) => page.next ? pages.length + 1 : undefined, enabled: !!user, refetchInterval: 10000 });
  const notifications = useQuery({ queryKey: ['notifications', user?.id], queryFn: () => api<Paginated<Notification>>('/notifications/'), enabled: !!user });
  if (!ready) return <Page title="My tickets"><Loading /></Page>; if (!user) return <Page title="My tickets"><SignInPrompt /></Page>;
  return <Page title="My tickets"><Text style={styles.notice}>Keep your QR private. Admission requires a live online check at the gate.</Text><Button title="Refresh my wallet" onPress={() => void queries.invalidateQueries()} /><Alert error={error ?? tickets.error ?? orders.error ?? notifications.error} />{tickets.isPending && <Loading />}{tickets.data?.pages.flatMap(page => page.results).map(ticket => <TicketCard key={ticket.id} ticket={ticket} />)}{tickets.data?.pages[0]?.count === 0 && <Text style={styles.muted}>Your paid tickets will appear here.</Text>}{tickets.hasNextPage && <Button title="More tickets" disabled={tickets.isFetchingNextPage} onPress={() => void tickets.fetchNextPage()} />}<Text style={styles.subtitle}>My orders</Text>{orders.data?.pages.flatMap(page => page.results).map(order => <View style={styles.card} key={order.id}><Text style={styles.text}>{order.event_title}</Text><Text style={styles.badge}>{order.status} · {money(order.total_minor, order.currency)}</Text><Text style={styles.muted}>Order {order.id}</Text>{order.status === 'PAYMENT_PROCESSING' && <Text style={styles.notice}>Awaiting server confirmation. A browser return does not confirm payment.</Text>}</View>)}{orders.hasNextPage && <Button title="More orders" onPress={() => void orders.fetchNextPage()} />}<Text style={styles.subtitle}>Notifications</Text>{notifications.data?.results.map(item => <View style={styles.card} key={item.id}><Text style={styles.text}>{item.subject}</Text><Text style={styles.muted}>{item.body}</Text>{!item.read_at && <Button title={`Mark read: ${item.subject}`} onPress={() => void api(`/notifications/${item.id}/read/`, post({})).then(() => queries.invalidateQueries({ queryKey: ['notifications'] })).catch(setError)} />}</View>)}</Page>;
}
