openapi: 3.0.3
info:
  title: Ticket API
  version: 1.0.0
  description: Event management and ticketing platform API
paths:
  /api/v1/auth/email-verification/:
    post:
      operationId: auth_email_verification_create
      tags:
      - auth
      security:
      - jwtAuth: []
      - cookieAuth: []
      responses:
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
          description: ''
  /api/v1/auth/email-verify/:
    post:
      operationId: auth_email_verify_create
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRequest'
        required: true
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
          description: ''
  /api/v1/auth/password-reset/:
    post:
      operationId: auth_password_reset_create
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetRequestRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ResetRequestRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ResetRequestRequest'
        required: true
      security:
      - {}
      responses:
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
          description: ''
  /api/v1/auth/password-reset/confirm/:
    post:
      operationId: auth_password_reset_confirm_create
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetConfirmRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ResetConfirmRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ResetConfirmRequest'
        required: true
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
          description: ''
  /api/v1/auth/register/:
    post:
      operationId: auth_register_create
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
        required: true
      security:
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistrationResult'
          description: ''
  /api/v1/auth/login/:
    post:
      operationId: auth_login_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPairRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPairRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPairRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
  /api/v1/auth/refresh/:
    post:
      operationId: auth_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SecureRefreshRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SecureRefreshRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SecureRefreshRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RefreshResult'
          description: ''
  /api/v1/auth/logout/:
    post:
      operationId: auth_logout_create
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogoutRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/LogoutRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/LogoutRequest'
        required: true
      security:
      - jwtAuth: []
      - cookieAuth: []
      responses:
        '204':
          description: No response body
  /api/v1/me/:
    get:
      operationId: me_retrieve
      tags:
      - me
      security:
      - jwtAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
          description: ''
    patch:
      operationId: me_partial_update
      tags:
      - me
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedProfileRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedProfileRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedProfileRequest'
      security:
      - jwtAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
          description: ''
  /api/v1/organizations/{id}/members/{membership_id}/:
    patch:
      operationId: organizations_members_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: membership_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - organizations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedRoleRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedRoleRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedRoleRequest'
      security:
      - jwtAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MembershipResult'
          description: ''
  /api/v1/organizations/{id}/invitations/:
    post:
      operationId: organizations_invitations_create
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - organizations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvitationCreateRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/InvitationCreateRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/InvitationCreateRequest'
        required: true
      security:
      - jwtAuth: []
      - cookieAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvitationResult'
          description: ''
  /api/v1/invitations/accept/:
    post:
      operationId: invitations_accept_create
      tags:
      - invitations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvitationAcceptRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/InvitationAcceptRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/InvitationAcceptRequest'
        required: true
      security:
      - jwtAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcceptanceResult'
          description: ''
  /api/v1/organizations/:
    get:
      operationId: organizations_list
      parameters:
      - name: ordering
        required: false
        in: query
        description: Which field to use when ordering the results.
        schema:
          type: string
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      tags:
      - organizations
      security:
      - jwtAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedOrganizationList'
          description: ''
    post:
      operationId: organizations_create
      tags:
      - organizations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrganizationRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/OrganizationRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/OrganizationRequest'
        required: true
      security:
      - jwtAuth: []
      - cookieAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
          description: ''
  /api/v1/organizations/{id}/:
    get:
      operationId: organizations_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - organizations
      security:
      - jwtAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
          description: ''
components:
  schemas:
    AcceptanceResult:
      type: object
      properties:
        organization_id:
          type: string
          format: uuid
          readOnly: true
        role:
          type: string
          readOnly: true
      required:
      - organization_id
      - role
    InvitationAcceptRequest:
      type: object
      properties:
        token:
          type: string
          minLength: 1
          maxLength: 2048
      required:
      - token
    InvitationCreateRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          minLength: 1
        role:
          $ref: '#/components/schemas/RoleEnum'
      required:
      - email
      - role
    InvitationResult:
      type: object
      properties:
        email:
          type: string
          format: email
        role:
          $ref: '#/components/schemas/RoleEnum'
        id:
          type: string
          format: uuid
          readOnly: true
        expires_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - email
      - expires_at
      - id
      - role
    LogoutRequest:
      type: object
      properties:
        refresh:
          type: string
          minLength: 1
      required:
      - refresh
    MembershipResult:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        role:
          type: string
          readOnly: true
      required:
      - id
      - role
    Message:
      type: object
      properties:
        message:
          type: string
          readOnly: true
      required:
      - message
    Organization:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        slug:
          type: string
          maxLength: 50
          pattern: ^[-a-zA-Z0-9_]+$
        name:
          type: string
          maxLength: 200
        owner:
          type: string
          format: uuid
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - created_at
      - id
      - name
      - owner
      - slug
    OrganizationRequest:
      type: object
      properties:
        slug:
          type: string
          minLength: 1
          maxLength: 50
          pattern: ^[-a-zA-Z0-9_]+$
        name:
          type: string
          minLength: 1
          maxLength: 200
      required:
      - name
      - slug
    PaginatedOrganizationList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Organization'
    PatchedProfileRequest:
      type: object
      properties:
        display_name:
          type: string
          maxLength: 150
    PatchedRoleRequest:
      type: object
      properties:
        role:
          $ref: '#/components/schemas/RoleEnum'
    Profile:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        email:
          type: string
          format: email
          readOnly: true
        display_name:
          type: string
          maxLength: 150
        email_verified_at:
          type: string
          format: date-time
          readOnly: true
          nullable: true
        created_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - created_at
      - email
      - email_verified_at
      - id
    RefreshResult:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - refresh
    RegisterRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          minLength: 1
          maxLength: 254
        display_name:
          type: string
          maxLength: 150
        password:
          type: string
          writeOnly: true
          minLength: 1
      required:
      - email
      - password
    RegistrationResult:
      type: object
      properties:
        user:
          allOf:
          - $ref: '#/components/schemas/Profile'
          readOnly: true
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - refresh
      - user
    ResetConfirmRequest:
      type: object
      properties:
        token:
          type: string
          minLength: 1
          maxLength: 2048
        user_id:
          type: string
          format: uuid
        password:
          type: string
          writeOnly: true
          minLength: 1
      required:
      - password
      - token
      - user_id
    ResetRequestRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          minLength: 1
      required:
      - email
    RoleEnum:
      enum:
      - MANAGER
      - EDITOR
      - FINANCE
      - SCANNER
      type: string
      description: |-
        * `MANAGER` - MANAGER
        * `EDITOR` - EDITOR
        * `FINANCE` - FINANCE
        * `SCANNER` - SCANNER
    SecureRefreshRequest:
      type: object
      properties:
        refresh:
          type: string
          minLength: 1
      required:
      - refresh
    TokenObtainPair:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - refresh
    TokenObtainPairRequest:
      type: object
      properties:
        email:
          type: string
          writeOnly: true
          minLength: 1
        password:
          type: string
          writeOnly: true
          minLength: 1
      required:
      - email
      - password
    TokenRequest:
      type: object
      properties:
        token:
          type: string
          minLength: 1
          maxLength: 2048
      required:
      - token
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
