# Generated by Django 5.0.6 on 2026-10-04 18:31

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("event_type", models.CharField(max_length=40)),
                ("aggregate_id", models.UUIDField()),
                ("deduplication_key", models.CharField(max_length=200, unique=True)),
                ("payload_redacted", models.JSONField(default=dict)),
                ("published_at", models.DateTimeField(null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("lease_until", models.DateTimeField(null=True)),
                ("failed_at", models.DateTimeField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("kind", models.CharField(max_length=40)),
                ("subject", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("read_at", models.DateTimeField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "outbox",
                    models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to="notifications.outboxevent"),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
            },
        ),
    ]
