# Generated by Django 5.0.6 on 2026-10-04 18:10

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0002_invitation_invitation_valid_invitation_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(max_length=100)),
                ("country_code", models.CharField(default="MG", max_length=2)),
                ("timezone", models.CharField(default="Indian/Antananarivo", max_length=64)),
                ("accessibility_info", models.TextField(blank=True)),
                ("layout_frozen", models.BooleanField(default=False)),
                ("layout_version", models.PositiveIntegerField(default=1)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venues",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VenueSection",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("code", models.SlugField()),
                ("name", models.CharField(max_length=100)),
                ("capacity", models.PositiveIntegerField()),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="sections", to="venues.venue"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("row_label", models.CharField(max_length=20)),
                ("seat_number", models.PositiveIntegerField()),
                ("label", models.CharField(max_length=50)),
                ("accessible", models.BooleanField(default=False)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="seats", to="venues.venuesection"
                    ),
                ),
            ],
            options={
                "ordering": ["row_label", "seat_number"],
            },
        ),
        migrations.AddConstraint(
            model_name="venuesection",
            constraint=models.UniqueConstraint(fields=("venue", "code"), name="unique_venue_section"),
        ),
        migrations.AddConstraint(
            model_name="seat",
            constraint=models.UniqueConstraint(
                fields=("section", "row_label", "seat_number"), name="unique_seat_coordinates"
            ),
        ),
    ]
