# Generated by Django 5.0.6 on 2026-10-04 18:10

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0002_invitation_invitation_valid_invitation_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventSeat",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventSection",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("capacity", models.PositiveIntegerField()),
                ("layout_version", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="EventTicketType",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("code", models.SlugField()),
                ("name", models.CharField(max_length=100)),
                (
                    "kind",
                    models.CharField(
                        choices=[("GENERAL", "General admission"), ("ASSIGNED", "Assigned seating")], max_length=8
                    ),
                ),
                ("price_minor", models.PositiveIntegerField()),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("quota", models.PositiveIntegerField()),
                ("per_order_limit", models.PositiveSmallIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("slug", models.SlugField()),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(db_index=True, default="Music", max_length=50)),
                ("start_at", models.DateTimeField(db_index=True)),
                ("end_at", models.DateTimeField()),
                ("event_timezone", models.CharField(default="Indian/Antananarivo", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                (
                    "seating_mode",
                    models.CharField(
                        choices=[("GENERAL", "General"), ("ASSIGNED", "Assigned"), ("MIXED", "Mixed")],
                        default="GENERAL",
                        max_length=10,
                    ),
                ),
                ("sales_start_at", models.DateTimeField()),
                ("sales_end_at", models.DateTimeField()),
                ("age_policy", models.CharField(default="All ages", max_length=200)),
                (
                    "cancellation_policy",
                    models.TextField(default="Refunds before the event for unused tickets. Simulated payments only."),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["start_at", "id"],
            },
        ),
    ]
