# Generated by Django 5.0.6 on 2026-10-04 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="venue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="venues.venue",
            ),
        ),
        migrations.AddField(
            model_name="eventseat",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="seats", to="events.event"
            ),
        ),
        migrations.AddField(
            model_name="eventseat",
            name="seat",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="venues.seat"),
        ),
        migrations.AddField(
            model_name="eventsection",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="sections", to="events.event"
            ),
        ),
        migrations.AddField(
            model_name="eventsection",
            name="venue_section",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="venues.venuesection"),
        ),
        migrations.AddField(
            model_name="eventseat",
            name="event_section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="seats", to="events.eventsection"
            ),
        ),
        migrations.AddField(
            model_name="eventtickettype",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="ticket_types", to="events.event"
            ),
        ),
        migrations.AddField(
            model_name="eventtickettype",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ticket_types",
                to="events.eventsection",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(fields=("organization", "slug"), name="unique_organization_event_slug"),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                check=models.Q(("start_at__lt", models.F("end_at"))), name="event_time_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                check=models.Q(("sales_start_at__lt", models.F("sales_end_at"))), name="event_sales_time_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                check=models.Q(("status__in", ["DRAFT", "PUBLISHED", "CANCELLED", "COMPLETED"])),
                name="event_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                check=models.Q(("seating_mode__in", ["GENERAL", "ASSIGNED", "MIXED"])), name="event_valid_mode"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventsection",
            constraint=models.UniqueConstraint(fields=("event", "venue_section"), name="unique_event_section"),
        ),
        migrations.AddConstraint(
            model_name="eventseat",
            constraint=models.UniqueConstraint(fields=("event", "seat"), name="unique_event_seat"),
        ),
        migrations.AddConstraint(
            model_name="eventtickettype",
            constraint=models.UniqueConstraint(fields=("event", "code"), name="unique_event_ticket_code"),
        ),
        migrations.AddConstraint(
            model_name="eventtickettype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "ASSIGNED")), fields=("section",), name="one_assigned_type_per_section"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventtickettype",
            constraint=models.CheckConstraint(
                check=models.Q(("kind__in", ["GENERAL", "ASSIGNED"])), name="ticket_type_valid_kind"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventtickettype",
            constraint=models.CheckConstraint(
                check=models.Q(("currency__in", ["EUR", "USD", "MGA"])), name="ticket_type_supported_currency"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventtickettype",
            constraint=models.CheckConstraint(
                check=models.Q(("per_order_limit__gt", 0), ("per_order_limit__lte", 20), ("quota__gt", 0)),
                name="ticket_type_positive_limits",
            ),
        ),
    ]
