# Generated by Django 5.0.6 on 2026-10-04 18:19

import uuid

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models

import apps.orders.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0002_initial"),
        ("reservations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "public_reference",
                    models.CharField(default=apps.orders.models.reference, max_length=24, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAYMENT_PROCESSING", "Payment_Processing"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                            ("PARTIALLY_REFUNDED", "Partially_Refunded"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("subtotal_minor", models.PositiveIntegerField()),
                ("discount_minor", models.PositiveIntegerField(default=0)),
                ("fees_minor", models.PositiveIntegerField(default=0)),
                ("tax_minor", models.PositiveIntegerField(default=0)),
                ("total_minor", models.PositiveIntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("expires_at", models.DateTimeField()),
                ("paid_at", models.DateTimeField(null=True)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("fingerprint", models.CharField(max_length=64)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="orders", to="events.event"
                    ),
                ),
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order",
                        to="reservations.reservation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="orders", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("quantity", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=100)),
                ("unit_price_minor", models.PositiveIntegerField()),
                ("discount_minor", models.PositiveIntegerField(default=0)),
                ("total_minor", models.PositiveIntegerField()),
                (
                    "event_seat",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="events.eventseat"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="items", to="orders.order"
                    ),
                ),
                (
                    "reservation_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="reservations.reservationitem"
                    ),
                ),
                (
                    "ticket_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="events.eventtickettype"),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["user", "created_at"], name="orders_orde_user_id_37fed6_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["event", "status"], name="orders_orde_event_i_17b8dc_idx"),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(fields=("user", "idempotency_key"), name="unique_user_order_key"),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "total_minor",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                django.db.models.expressions.CombinedExpression(
                                    models.F("subtotal_minor"), "-", models.F("discount_minor")
                                ),
                                "+",
                                models.F("fees_minor"),
                            ),
                            "+",
                            models.F("tax_minor"),
                        ),
                    )
                ),
                name="order_balanced_money",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                check=models.Q(("discount_minor__lte", models.F("subtotal_minor"))), name="order_discount_bound"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gt", 0)), name="order_item_quantity_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "total_minor",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.F("quantity"), "*", models.F("unit_price_minor")
                            ),
                            "-",
                            models.F("discount_minor"),
                        ),
                    )
                ),
                name="order_item_balanced_money",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("event_seat__isnull", False)),
                fields=("order", "event_seat"),
                name="one_order_item_per_seat",
            ),
        ),
    ]
