# Generated by Django 5.0.6 on 2026-10-04 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="entity_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="event",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="events.event"
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="ip_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="metadata_redacted",
            field=models.JSONField(default=dict),
        ),
    ]
