import { expect, test } from '@playwright/test';
const shots = process.cwd().endsWith('/web') ? '../docs/screenshots/' : 'docs/screenshots/';
const password = process.env.DEMO_PASSWORD ?? 'synthetic-demo-password-94!';
async function login(page: import('@playwright/test').Page, role: string) { await page.goto('/account'); await page.getByLabel('Email', { exact: true }).fill(`demo-${role}@ticket.example`); await page.getByLabel('Password', { exact: true }).fill(password); await page.getByRole('button', { name: 'Sign in', exact: true }).click(); await expect(page.getByRole('heading', { name: `Hello, Synthetic ${role[0].toUpperCase() + role.slice(1)}.` })).toBeVisible(); }
test('public responsive discovery, assigned hold, cancellation and simulated checkout', async ({ page }) => {
  await page.goto('/'); await expect(page.getByRole('heading', { name: 'Garden Sessions' })).toBeVisible(); await page.screenshot({ path: shots + 'discovery-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 }); await page.screenshot({ path: shots + 'discovery-phone.png', fullPage: true }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await login(page, 'owner'); await page.getByRole('link', { name: 'Discover', exact: true }).click(); await page.getByRole('heading', { name: 'An Evening on Stage' }).click(); const seat = page.getByRole('button', { name: /^A1, accessible, available$/ }); await seat.click(); await page.getByRole('button', { name: 'Hold selected tickets ↗' }).click(); await expect(page.getByText(/Held for/)).toBeVisible(); await page.getByRole('button', { name: 'Release tickets and start again' }).click(); await expect(seat).toBeEnabled();
  await page.getByRole('link', { name: 'Discover', exact: true }).click(); await page.getByRole('heading', { name: 'Garden Sessions' }).click(); await page.getByLabel('Quantity').fill('2'); await page.getByRole('button', { name: 'Hold selected tickets ↗' }).click(); await expect(page.getByText(/Held for/)).toBeVisible(); await page.getByRole('button', { name: 'Continue to checkout' }).click(); await page.getByRole('button', { name: /Pay .* in test mode/ }).click(); await expect(page.getByRole('heading', { name: 'You’re going!' })).toBeVisible(); await page.getByRole('link', { name: 'View my tickets' }).click(); await expect(page.getByRole('img', { name: /Admission QR/ }).first()).toBeVisible(); await page.screenshot({ path: shots + 'wallet-phone.png', fullPage: true, mask: [page.locator('.qr')], maskColor: '#e4eccf' });
});
test('organizer metrics and partial refund use the real scoped API', async ({ page }) => { await login(page, 'owner'); await page.getByRole('link', { name: 'Workspace', exact: true }).click(); await expect(page.getByRole('heading', { name: 'Your workspace' })).toBeVisible(); await page.getByRole('button', { name: 'Reports', exact: true }).click(); await page.getByLabel('Report event').selectOption({ label: 'Garden Sessions' }); await expect(page.getByText('Net simulated revenue')).toBeVisible(); await page.setViewportSize({ width: 1440, height: 1000 }); await page.screenshot({ path: shots + 'organizer-reports.png', fullPage: true }); await page.locator('article').filter({ hasText: 'Garden Sessions' }).getByRole('button', { name: 'Choose admissions to refund' }).first().click(); await expect(page.getByRole('heading', { name: /^Refund TK-/ })).toBeVisible(); await page.locator('.panel input[type=checkbox]').first().check(); await page.getByLabel('Refund reason').fill('Synthetic end-to-end partial refund'); await page.getByRole('button', { name: 'Refund selected admissions' }).click(); await expect(page.getByRole('status')).toHaveText('Selected admissions refunded in test mode.'); });
test('scanner sees only assigned events and rejects an invalid QR online', async ({ page }) => { await login(page, 'scanner'); await page.getByRole('link', { name: 'Workspace', exact: true }).click(); await page.getByRole('link', { name: 'Gate scanner ↗' }).click(); await expect(page.getByText('Online verification only. Scan tickets for your assigned events.')).toBeVisible(); await page.getByLabel('Assigned event').selectOption({ label: 'Garden Sessions' }); await page.getByLabel('QR token or ticket URL').fill('synthetic-invalid-token'); await page.getByRole('button', { name: 'Check admission' }).click(); await expect(page.getByText('INVALID — do not admit', { exact: true })).toBeVisible(); });
