# Generated by Django 5.0.6 on 2026-10-04 18:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0002_initial"),
        ("orders", "0001_initial"),
        ("organizations", "0003_eventstaffassignment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("code", models.CharField(max_length=40)),
                (
                    "kind",
                    models.CharField(choices=[("PERCENT", "Percent"), ("FIXED", "Fixed minor units")], max_length=7),
                ),
                ("amount", models.PositiveIntegerField()),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("usage_limit", models.PositiveIntegerField(default=100)),
                ("per_user_limit", models.PositiveSmallIntegerField(default=1)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("active", models.BooleanField(default=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="events.event"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotions",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PromotionRedemption",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("amount_minor", models.PositiveIntegerField()),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotion_redemption",
                        to="orders.order",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redemptions",
                        to="promotions.promotion",
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="promotion",
            constraint=models.UniqueConstraint(fields=("organization", "code"), name="unique_promotion_code"),
        ),
        migrations.AddConstraint(
            model_name="promotion",
            constraint=models.CheckConstraint(
                check=models.Q(("start_at__lt", models.F("end_at"))), name="promotion_time_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="promotion",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("kind", "FIXED"), models.Q(("amount__lte", 100), ("kind", "PERCENT")), _connector="OR"
                ),
                name="promotion_valid_amount",
            ),
        ),
        migrations.AddConstraint(
            model_name="promotion",
            constraint=models.CheckConstraint(
                check=models.Q(("per_user_limit__gt", 0), ("usage_limit__gt", 0)), name="promotion_positive_limits"
            ),
        ),
    ]
