# Generated by Django 5.0.6 on 2026-10-04 18:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentAttempt",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("MOCK", "Mock"), ("STRIPE_TEST", "Stripe test")], default="MOCK", max_length=11
                    ),
                ),
                ("provider_payment_id", models.CharField(blank=True, max_length=200, null=True)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("fingerprint", models.CharField(max_length=64)),
                ("amount_minor", models.PositiveIntegerField()),
                ("currency", models.CharField(max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("PENDING", "Pending"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="CREATED",
                        max_length=10,
                    ),
                ),
                ("checkout_url", models.URLField(blank=True, max_length=2000)),
                ("payment_intent_id", models.CharField(blank=True, max_length=200)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="payments", to="orders.order"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentEventInbox",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("provider", models.CharField(max_length=11)),
                ("event_id", models.CharField(max_length=200)),
                ("payload_digest", models.CharField(max_length=64)),
                ("processed_at", models.DateTimeField(null=True)),
                ("outcome", models.CharField(blank=True, max_length=30)),
                (
                    "payment",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="payments.paymentattempt"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("amount_minor", models.PositiveIntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("reason", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("SUCCEEDED", "Succeeded"), ("FAILED", "Failed")],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("provider_ref", models.CharField(blank=True, max_length=200)),
                ("completed_at", models.DateTimeField(null=True)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("fingerprint", models.CharField(max_length=64)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="refunds", to="orders.order"
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="payments.paymentattempt",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.UniqueConstraint(fields=("order", "idempotency_key"), name="unique_order_payment_key"),
        ),
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_payment_id__isnull", False)),
                fields=("provider", "provider_payment_id"),
                name="unique_provider_payment",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["CREATED", "PENDING", "SUCCEEDED"])),
                fields=("order",),
                name="one_payable_attempt_per_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenteventinbox",
            constraint=models.UniqueConstraint(fields=("provider", "event_id"), name="unique_payment_event"),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.UniqueConstraint(fields=("order", "idempotency_key"), name="unique_order_refund_key"),
        ),
    ]
