# Generated by Django 5.2.17 on 2026-10-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentattempt",
            name="scenario",
            field=models.CharField(default="success", max_length=10),
        ),
    ]
