# Generated by Django 5.0.6 on 2026-10-04 18:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.orders.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0002_initial"),
        ("orders", "0001_initial"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("admission_index", models.PositiveSmallIntegerField()),
                ("admission_price_minor", models.PositiveIntegerField()),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("public_code", models.CharField(default=apps.orders.models.reference, max_length=24, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("VALID", "Valid"),
                            ("USED", "Used"),
                            ("REVOKED", "Revoked"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="VALID",
                        max_length=10,
                    ),
                ),
                ("used_at", models.DateTimeField(null=True)),
                ("revoked_at", models.DateTimeField(null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="tickets", to="events.event"
                    ),
                ),
                (
                    "event_seat",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="events.eventseat"),
                ),
                (
                    "holder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="tickets", to="orders.orderitem"
                    ),
                ),
                (
                    "refund",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="payments.refund",
                    ),
                ),
                (
                    "ticket_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="events.eventtickettype"),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
                "indexes": [models.Index(fields=["event", "status"], name="tickets_tic_event_i_d07e31_idx")],
            },
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("order_item", "admission_index"), name="one_ticket_per_admission"
            ),
        ),
    ]
