# Generated by Django 5.0.6 on 2026-10-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="inventory_released",
            field=models.BooleanField(default=False),
        ),
    ]
