# Generated by Django 5.0.6 on 2026-10-04 18:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("ACCEPTED", "Accepted"),
                            ("DUPLICATE", "Duplicate"),
                            ("INVALID", "Invalid"),
                            ("REVOKED", "Revoked"),
                            ("WRONG_EVENT", "Wrong_Event"),
                            ("CLOSED", "Closed"),
                        ],
                        max_length=11,
                    ),
                ),
                ("device_id", models.CharField(blank=True, max_length=100)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("fingerprint", models.CharField(max_length=64)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="check_ins", to="events.event"
                    ),
                ),
                (
                    "scanned_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
