# Generated by Django 5.0.6 on 2026-10-04 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("checkins", "0001_initial"),
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkin",
            name="ticket",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="check_ins", to="tickets.ticket"
            ),
        ),
        migrations.AddConstraint(
            model_name="checkin",
            constraint=models.UniqueConstraint(
                condition=models.Q(("result", "ACCEPTED")), fields=("ticket",), name="one_accepted_check_in"
            ),
        ),
        migrations.AddConstraint(
            model_name="checkin",
            constraint=models.UniqueConstraint(
                fields=("scanned_by", "idempotency_key"), name="unique_scanner_check_in_key"
            ),
        ),
    ]
