import { useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { keepPreviousData, useQuery } from '@tanstack/react-query';
import type { Paginated, TicketEvent } from '../../packages/api-client/src';
import { useSession } from './session';
import { Alert, Empty, Loading } from './ui';
import { Icon } from './Icon';
import { Reveal } from './motion';
import EventCard from './EventCard';

export default function Discover() {
  const { api } = useSession(); const [filters, setFilters] = useSearchParams(); const [view, setView] = useState<'grid' | 'list'>('grid');
  const search = filters.get('search') ?? ''; const category = filters.get('category') ?? ''; const city = filters.get('city') ?? '';
  const requestedPage = Number(filters.get('page')); const page = Number.isFinite(requestedPage) ? Math.max(1, Math.floor(requestedPage || 1)) : 1; const ordering = filters.get('ordering') === '-created_at' ? '-created_at' : 'start_at';
  const params = new URLSearchParams({ search, category, city, page: String(page), ordering });
  const events = useQuery({ queryKey: ['events', params.toString()], queryFn: () => api<Paginated<TicketEvent>>(`/events/?${params}`), placeholderData: keepPreviousData });
  function change(name: string, value: string) { const next = new URLSearchParams(filters); if (value) next.set(name, value); else next.delete(name); if (name !== 'page') next.delete('page'); setFilters(next, { replace: true }); }
  return <>
    <section className="hero"><div className="hero-copy"><p className="eyebrow"><span className="live-dot" />Your next good moment</p><h1>Life happens<br /><span>when you</span><br /><em>show up.</em></h1><p>Small stages. Big ideas. Unforgettable nights.<br />Find your people, one experience at a time.</p><div className="hero-actions"><a className="primary button" href="#events">Explore events <Icon name="arrowUp" /></a><Link className="text-link" to="/workspace">Create an event <Icon name="arrow" size={18} /></Link></div><div className="hero-assurance"><Icon name="shield" size={17} /><span>One place for your plans, tickets & good company.</span></div></div>
      <div className="hero-art" aria-hidden="true"><div className="art-grain" /><div className="art-orbit orbit-one" /><div className="art-orbit orbit-two" /><span className="art-caption">YOUR INVITATION TO GO</span><div className="art-ticket ticket-shadow"><span>MAKE A MEMORY</span></div><div className="art-ticket"><div className="art-ticket-top"><Icon name="ticket" size={23} /><span>TICKET / ADMIT ONE</span></div><div className="art-ticket-middle"><span>THE NEXT CHAPTER</span><strong>Be<br /><em>there.</em></strong><span>IS WAITING FOR YOU</span></div><div className="art-ticket-bottom"><div className="art-barcode" /><span>GOOD MOMENTS. TOGETHER.</span></div></div><span className="art-sticker"><Icon name="sparkle" size={23} />Not just<br />another night.</span><span className="art-coordinate">48° OF POSSIBILITY · ∞ MEMORIES</span></div>
    </section>
    <div className="experience-strip"><span><Icon name="music" />Live music</span><span><Icon name="sparkle" />Big ideas</span><span><Icon name="ticket" />Small stages</span><span><Icon name="user" />Your people</span><span className="strip-note">A little less ordinary.</span></div>
    <section id="events" className="discovery-section"><Reveal><div className="section-heading"><div><p className="eyebrow">Go where the good things are</p><h2>Find your next event<span className="heading-dot">.</span></h2><p className="muted">A fresh reason to leave the house.</p></div><div className="view-switch" role="group" aria-label="Event display"><button className={view === 'grid' ? 'active' : ''} aria-label="Grid view" aria-pressed={view === 'grid'} onClick={() => setView('grid')}><Icon name="grid" size={18} /></button><button className={view === 'list' ? 'active' : ''} aria-label="List view" aria-pressed={view === 'list'} onClick={() => setView('list')}><Icon name="list" size={18} /></button></div></div></Reveal>
      <form className="filters" onSubmit={event => event.preventDefault()}><label className="search-label"><span>Search events</span><div className="input-icon"><Icon name="search" /><input type="search" placeholder="An artist, a feeling, a new idea…" value={search} onChange={event => change('search', event.target.value)} /></div></label><label><span>City</span><div className="input-icon"><Icon name="pin" /><input value={city} placeholder="Anywhere" onChange={event => change('city', event.target.value)} /></div></label><label><span>Sort by</span><select value={ordering} onChange={event => change('ordering', event.target.value)}><option value="start_at">Coming up first</option><option value="-created_at">Recently added</option></select></label></form>
      <div className="discovery-tools"><div className="category-chips" role="group" aria-label="Event category">{['', 'Music', 'Theatre', 'Technology'].map(value => <button key={value} aria-pressed={category === value} className={`category-chip ${category === value ? 'active' : ''}`} onClick={() => change('category', value)}>{value === 'Music' && <Icon name="music" size={15} />}{value === 'Theatre' && <Icon name="ticket" size={15} />}{value === 'Technology' && <Icon name="sparkle" size={15} />}{value || 'All experiences'}</button>)}</div><span className="result-count" aria-live="polite">{events.data?.count ?? '…'} events {events.isFetching && events.data ? '· updating' : 'to explore'}</span></div>
      {(search || city || category) && <div className="filter-summary"><span>Filtered{category ? ` · ${category}` : ''}{city ? ` · ${city}` : ''}{search ? ` · “${search}”` : ''}</span><button className="text-link" onClick={() => setFilters({}, { replace: true })}>Clear filters <Icon name="close" size={14} /></button></div>}
      {events.isPending ? <Loading cards /> : <Alert error={events.error} />}{events.data && !events.data.results.length && <Empty><Icon name="search" size={36} /><h3>No events found</h3><p>Try another search or category. Your next moment is out there.</p><button className="primary" onClick={() => setFilters({}, { replace: true })}>Reset filters</button></Empty>}
      <div className={`event-grid ${view === 'list' ? 'event-list' : ''}`} aria-busy={events.isFetching}>{events.data?.results.map((event, index) => <Reveal key={event.id} delay={index % 3 * 70}><EventCard event={event} index={index} /></Reveal>)}</div>
      {events.data && (events.data.next || events.data.previous) && <div className="pagination"><button disabled={!events.data.previous || events.isPlaceholderData} onClick={() => change('page', String(page - 1))}>Previous</button><span>Page {page}</span><button disabled={!events.data.next || events.isPlaceholderData} onClick={() => change('page', String(page + 1))}>Next</button></div>}
    </section>
    <Reveal><section className="organize-banner"><div className="banner-copy"><p className="eyebrow">For the ones who make it happen</p><h2>Your idea.<br /><em>Their next favourite memory.</em></h2><p>Set the stage. Build your team. Bring people together.<br />We’ll help with everything in between.</p><Link className="primary button" to="/workspace">Open your workspace <Icon name="arrowUp" /></Link></div><div className="banner-art" aria-hidden="true"><span className="banner-circle" /><div className="banner-mini-ticket"><Icon name="sparkle" size={32} /><strong>MAKE<br />IT HAPPEN.</strong><span>ALL GREAT EVENTS START SOMEWHERE</span></div></div></section></Reveal>
    <section className="how-it-works"><Reveal><p className="eyebrow">Less friction. More feeling.</p><h2>The good part is getting there.</h2></Reveal><div className="steps-grid">{[{ icon: 'compass' as const, title: 'Find your thing.', copy: 'Explore music, stages and ideas. Save the ones that feel like you.' }, { icon: 'ticket' as const, title: 'Make it yours.', copy: 'Choose your tickets or an exact seat. Your place, held while you decide.' }, { icon: 'scan' as const, title: 'Just show up.', copy: 'Keep your tickets close in your wallet. One scan, and you’re in.' }].map((step, index) => <Reveal key={step.title} delay={index * 80}><div className="how-step"><span className="step-icon"><Icon name={step.icon} size={25} /></span><span className="step-index">0{index + 1}</span><h3>{step.title}</h3><p>{step.copy}</p></div></Reveal>)}</div></section>
    <p className="demo-disclaimer"><Icon name="shield" size={15} />Portfolio demo · Synthetic events · All payments are simulated.</p>
  </>;
}
