# Generated by Django 5.0.6 on 2026-10-04 18:19

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_initial"),
        ("organizations", "0002_invitation_invitation_valid_invitation_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventStaffAssignment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_assignments",
                        to="events.event",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_assignments",
                        to="organizations.membership",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="eventstaffassignment",
            constraint=models.UniqueConstraint(fields=("event", "membership"), name="unique_event_staff_assignment"),
        ),
    ]
