# Generated by Django 5.0.6 on 2026-10-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0003_eventstaffassignment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("SUSPENDED", "Suspended")], default="ACTIVE", max_length=9
            ),
        ),
    ]
